repos:
   -   repo: local
       hooks:
          - id: unittest
            name: unittest
            entry:  bash -c 'cd backend && python manage.py test npc_creator.tests'
            language: python
            'types': [ python ]
            args: [  ]
            additional_dependencies: [
              django,
              openai,
              Pillow,
              django-cors-headers,
              djangorestframework
            ]
            pass_filenames: false
