# Generated by Django 4.1.7 on 2023-03-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='key',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value',
            field=models.TextField(db_index=True),
        ),
    ]
