# Generated by Django 4.1.7 on 2023-03-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_creator', '0002_alter_attribute_key_alter_attribute_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='image_generator_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='image_generator_state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='npc',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='user_prompt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
