# Generated by Django 4.1.7 on 2023-03-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npc_creator", "0003_alter_npc_image_generator_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="npc",
            name="image_generator_state",
            field=models.CharField(blank=True, default="init", max_length=20),
        ),
    ]
