# Generated by Django 4.1.7 on 2023-03-29 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("npc_creator", "0005_exampleimage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExampleImage",
            new_name="TemplateImage",
        ),
    ]
