# Generated by Django 4.1.8 on 2023-04-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npc_creator", "0009_panelimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="npc",
            name="default_image_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="npc",
            name="max_image_number",
            field=models.IntegerField(default=0),
        ),
    ]
