# Generated by Django 4.1.8 on 2023-04-18 23:08

from django.db import migrations
import os
from npc_creator.models import Npc


def migrate(*args, **kwargs):
    for npc in Npc.objects.all():
        if not npc.image_url:
            continue

        filename, extension = os.path.splitext(npc.image_url)
        index = int(filename.split('-')[-1])
        npc.image_url = filename[:filename.rfind('-')] + '-{counter}' + extension
        npc.max_image_number = 4
        npc.default_image_number = index
        npc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('npc_creator', '0010_npc_default_image_number_npc_max_image_number'),
    ]

    operations = [
        migrations.RunPython(migrate, )
    ]
