# Generated by Django 4.1.8 on 2023-08-24 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("npc_creator", "0013_npc_access_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="GptRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.JSONField()),
                ("output", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ST", "Started"),
                            ("CO", "Completed"),
                            ("FF", "Failed"),
                        ],
                        default="ST",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="npc",
            name="access_key",
        ),
        migrations.AddField(
            model_name="npc",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="npc",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="panelimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="panelimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="templateimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="templateimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="npc",
            name="state",
            field=models.CharField(
                choices=[("CR", "Created"), ("MO", "Moderated"), ("FA", "Failed")],
                default="CR",
                max_length=2,
            ),
        ),
    ]
