# Generated by Django 4.1.8 on 2023-10-21 09:27

from django.db import migrations, models
import django.db.models.deletion

from npc_creator import config
from npc_creator.models import Entity
import os


def image_structure(*args, **kwargs):
    npcs = Entity.objects.all()
    for npc in npcs:
        for i in range(npc.max_image_number + 1):
            file = npc.image_url.format(pk=npc.id, counter=i)
            path = os.path.join(config.PUBLIC_NPC_IMAGE_PATH, file)
            if os.path.isfile(path):
                npc.images.append(file)

        npc.save()


class Migration(migrations.Migration):
    dependencies = [
        ("npc_creator", "0015_add_image_generation"),
    ]

    operations = [
        migrations.RunPython(image_structure),
    ]
