# Generated by Django 4.1.8 on 2023-10-21 09:27

from django.db import migrations, models



class Migration(migrations.Migration):
    dependencies = [
        ("npc_creator", "0015_add_image_generation"),
    ]

    operations = [
    ]
