# Generated by Django 4.1.8 on 2023-10-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_creator', '0022_alter_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='image_url',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
