# Generated by Django 4.1.8 on 2023-10-21 09:27

from django.db import migrations, models
import django.db.models.deletion

from npc_creator import config
from npc_creator.models import Entity
import os

from npc_creator.models.image import Image



class Migration(migrations.Migration):
    dependencies = [
        ("npc_creator", "0024_image_score"),
    ]

    operations = [

    ]
