# Generated by Django 4.1.8 on 2023-10-27 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npc_creator', '0026_migrate_default_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='template',
        ),
        migrations.AddField(
            model_name='image',
            name='generation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='npc_creator.imagegeneration'),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='npc_creator.templateimage'),
        ),
    ]
