# Generated by Django 4.1.8 on 2023-10-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npc_creator", "0027_remove_image_template_image_generation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gptrequest",
            name="kind",
            field=models.TextField(blank=True),
        ),
    ]
