# Generated by Django 4.1.8 on 2023-11-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npc_creator", "0028_gptrequest_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="generation",
            field=models.IntegerField(default=0),
        ),
    ]
