# Generated by Django 4.1.8 on 2023-11-09 00:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("npc_creator", "0029_attribute_generation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="npc",
            name="image_generator_state",
        ),
        migrations.RemoveField(
            model_name="npc",
            name="images",
        ),
        migrations.RemoveField(
            model_name="npc",
            name="max_image_number",
        ),
    ]
