# Generated by Django 4.1.8 on 2023-11-10 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "npc_creator",
            "0030_remove_npc_image_generator_state_remove_npc_images_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="npc",
            name="default_image_number",
        ),
        migrations.RemoveField(
            model_name="npc",
            name="state",
        ),
    ]
