# Generated by Django 4.1.8 on 2023-11-10 22:34

from django.db import migrations, models

from django.db import migrations


def convert_attributes_data(apps, schema_editor):
    Npc = apps.get_model('npc_creator', 'Npc')

    for npc in Npc.objects.all():
        npc_attributes = npc.attribute_set.all()

        attributes_json = {attr.key: [attr.value] for attr in npc_attributes}

        npc.attributes = attributes_json
        npc.save()


class Migration(migrations.Migration):
    dependencies = [
        ("npc_creator", "0032_remove_npc_user_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="npc",
            name="attributes",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.RunPython(convert_attributes_data)
    ]
