# Generated by Django 4.1.8 on 2023-11-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npc_creator", "0033_npc_attributes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="npc",
            name="attributes",
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name="Attribute",
        ),
    ]
