# Generated by Django 4.1.8 on 2023-11-11 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("npc_creator", "0036_entity_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="Npc",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("npc_creator.entity",),
        ),
    ]
