# Generated by Django 4.1.8 on 2023-11-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npc_creator", "0039_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Custom",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("npc_creator.entity",),
        ),
        migrations.AlterField(
            model_name="entity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("Npc", "Npc"),
                    ("Location", "Location"),
                    ("Custom", "Custom"),
                    ("Critter", "Critter"),
                    ("Vehicle", "Vehicle"),
                ],
                max_length=20,
            ),
        ),
    ]
