# Generated by Django 4.1.8 on 2023-11-10 22:34

from django.db import migrations, models

from django.db import migrations
from gevent import os

from npc_creator import config
from npc_creator.services.image_generation.create_thumbnails import create_thumbnail


def bulk_thumbnails(apps, schema_editor):
    def entity_directory(self, entity_type):
        return os.path.join(config.PUBLIC_ENTITY_IMAGE_PATH, entity_type + "s")

    Image = apps.get_model("npc_creator", "Image")

    for image in Image.objects.all():
        if not image.entity:
            continue

        create_thumbnail(
            os.path.join(
                entity_directory(image.entity, image.entity.kind.lower()), image.name
            )
        )
        # removes the ext
        image.name = os.path.splitext(image.name)[0]
        image.save()


class Migration(migrations.Migration):
    dependencies = [
        ("npc_creator", "0041_feedback"),
    ]

    operations = [
        migrations.RunPython(bulk_thumbnails),
    ]
