# Generated by Django 4.1.13 on 2024-04-02 21:59

from django.db import migrations
from django.db.migrations import RunPython

from npc_creator.models import Npc


def convert_attributes(apps, schema_editor):
    for npc in Npc.objects.all():
        npc.attributes = _convert_attributes(npc, npc.attributes)
        npc.save()


def _convert_attributes(entity, attributes):
    changes = {
        "Konstitution (von 1-6)": "Konstitution",
        "Geschicklichkeit (von 1-6)": "Geschicklichkeit",
        "Reaktion (von 1-6)": "Reaktion",
        "Stärke (von 1-6)": "Stärke",
        "Willenskraft (von 1-6)": "Willenskraft",
        "Logik (von 1-6)": "Logik",
        "Intuition (von 1-6)": "Intuition",
        "Charisma (von 1-6)": "Charisma",
        "Glück (von 1-6)": "Edge",
        "Magie (von 0-6)": "Magie",
        "Resonanz (von 0-6)": "Resonanz",
    }

    attributes = {changes.get(k, k): v for k, v in attributes.items()}
    return attributes


class Migration(migrations.Migration):

    dependencies = [
        ("npc_creator", "0043_clean_npc_attributes"),
    ]

    operations = [
        migrations.RunPython(convert_attributes, reverse_code=RunPython.noop),
    ]
