# Generated by Django 4.1.13 on 2024-06-22 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("npc_creator", "0045_favorite_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="collection",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="npc_creator.collection",
            ),
            preserve_default=False,
        ),
    ]
