# Generated by Django 4.1.13 on 2024-07-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("npc_creator", "0047_singular_properties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("Npc", "Npc"),
                    ("Location", "Location"),
                    ("Custom", "Custom"),
                    ("Critter", "Critter"),
                    ("Vehicle", "Vehicle"),
                    ("Objects", "Objects"),
                ],
                max_length=20,
            ),
        ),
    ]
