# Generated by Django 4.1.13 on 2024-07-28 11:15

from django.db import migrations, models


def set_published(apps, schema_editor):
    Entity = apps.get_model("npc_creator", "Entity")
    for entity in Entity.objects.all():
        entity.state = "Published"
        entity.save()


class Migration(migrations.Migration):

    dependencies = [
        ("npc_creator", "0052_auto_20240718_1229"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="state",
            field=models.CharField(
                choices=[
                    ("Unpublished", "Unpublished"),
                    ("Private", "Private"),
                    ("Published", "Published"),
                ],
                default="Unpublished",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_published, reverse_code=migrations.RunPython.noop),
    ]
