# Generated by Django 4.1.13 on 2024-10-03 14:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("npc_creator", "0054_favorite_created_at_favorite_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="collection",
            unique_together={("name", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("entity", "collection")},
        ),
    ]
