# Generated by Django 4.1.13 on 2024-10-05 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("npc_creator", "0055_alter_collection_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
